language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t reactapp/netflix -f Dockerfile.dev .

script:
  - docker run -e CI=true reactapp/netflix npm run test -- --coverage